version: '3.9'

services:
  nest_api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest_api
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
      - FLASK_SERVICE_URL=http://flask_service:5000/summarize
    depends_on:
      - postgres
      - flask_service

  nest_api_test:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest_api_test
    working_dir: /app
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
      - FLASK_SERVICE_URL=http://flask_service:5000/summarize
    depends_on:
      - postgres
      - flask_service
    command: ["npm", "run", "test"]

  nest_api_seed:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest_api_seed
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    command: ["npm", "run", "seed"]

  flask_service:
    build:
      context: ./services/flask-summarizer
      dockerfile: Dockerfile
    container_name: flask_service
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma_migrate:
    image: node:18
    container_name: prisma_migrate
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    command: ["npx", "prisma", "migrate", "deploy"]

volumes:
  postgres_data:
